development:
  adapter: postgresql
  encoding: unicode
  database: bartville_development
  pool: 5
  username: postgres
  password: 0s5perd5per!

production:
  adapter: postgresql
  encoding: unicode
  database: bartville_production
  pool: 5
  username: postgres
  password: 0s5perd5per!